### ISSUE TITLE
UnboundLocalError while training

### ISSUE THREAD

**Issue by alarzaki** [ithet1007/MTL-SegTHOR#2]
Hi,
I tried to run the training using your code but after a few epochs, it keeps throwing this error:

`Traceback (most recent call last):
  File "main.py", line 403, in <module>
    main(args)
  File "main.py", line 223, in main
    if  max_precision <= eval_precision:
UnboundLocalError: local variable 'max_precision' referenced before assignment`

Could you please look at what could be causing this?

**Comment by GuobinZhangTJU** [comment]
> Hi,
> I tried to run the training using your code but after a few epochs, it keeps throwing this error:
> 
> `Traceback (most recent call last): File "main.py", line 403, in <module> main(args) File "main.py", line 223, in main if max_precision <= eval_precision: UnboundLocalError: local variable 'max_precision' referenced before assignment`
> 
> Could you please look at what could be causing this?

because max_precision was not initialized~
